number:
- platform: toptronic
  name: Modulazione ventilazione normale
  device_type: HV
  device_addr: ${TT_HV_addr}
  device_id: ${TT_HV_device_id}
  function_group: 50
  function_number: 0
  datapoint: 40651
  id: HV_50_0_40651_23623_set
  type: U8
  min_value: 15
  max_value: 100
  step: 1
  decimal: 0
  unit_of_measurement: '%'
  icon: mdi:percent
  device_class: power_factor
- platform: toptronic
  name: Modulazione ventilazione risparmio
  device_type: HV
  device_addr: ${TT_HV_addr}
  device_id: ${TT_HV_device_id}
  function_group: 50
  function_number: 0
  datapoint: 40686
  id: HV_50_0_40686_23624_set
  type: U8
  min_value: 15
  max_value: 100
  step: 1
  decimal: 0
  unit_of_measurement: '%'
  icon: mdi:percent
  device_class: power_factor
- platform: toptronic
  name: "Valore nominale umidit\xE0"
  device_type: HV
  device_addr: ${TT_HV_addr}
  device_id: ${TT_HV_device_id}
  function_group: 50
  function_number: 0
  datapoint: 40687
  id: HV_50_0_40687_23626_set
  type: U8
  min_value: 30
  max_value: 65
  step: 1
  decimal: 0
  unit_of_measurement: '%'
  icon: mdi:water-percent
  device_class: humidity
select:
- platform: toptronic
  name: Selezione modo funzion.to ventilazione
  device_type: HV
  device_addr: ${TT_HV_addr}
  device_id: ${TT_HV_device_id}
  function_group: 50
  function_number: 0
  datapoint: 40650
  id: HV_50_0_40650_23622_set
  options:
  - Stand-by
  - Settimana 1
  - Settimana 2
  - Modo costante, valore nominale 40651
  - Modo risparmio, valore nominale DAP40686
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
