sensor:
- platform: toptronic
  name: Normal ventilation modulation
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 40651
  id: HV_50_0_40651
  type: U8
  unit_of_measurement: '%'
  icon: mdi:percent
  device_class: power_factor
  state_class: measurement
  internal: true
- platform: toptronic
  name: Eco ventilation modulation
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 40686
  id: HV_50_0_40686
  type: U8
  unit_of_measurement: '%'
  icon: mdi:percent
  device_class: power_factor
  state_class: measurement
  internal: true
- platform: toptronic
  name: Ventilation modulation
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 38606
  id: HV_50_0_38606
  type: U8
  unit_of_measurement: '%'
  icon: mdi:percent
  device_class: power_factor
  state_class: measurement
- platform: toptronic
  name: Humidity set value
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 40687
  id: HV_50_0_40687
  type: U8
  unit_of_measurement: '%'
  icon: mdi:water-percent
  device_class: humidity
  state_class: measurement
  internal: true
- platform: toptronic
  name: Humidity extract air
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 37600
  id: HV_50_0_37600
  type: U8
  unit_of_measurement: '%'
  icon: mdi:water-percent
  device_class: humidity
  state_class: measurement
- platform: toptronic
  name: Outside air temp.
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 0
  id: HV_50_0_0
  type: S16
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
  unit_of_measurement: "\xB0C"
  icon: mdi:temperature-celsius
  device_class: temperature
  state_class: measurement
- platform: toptronic
  name: Extract air temp.
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 37602
  id: HV_50_0_37602
  type: S16
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
  unit_of_measurement: "\xB0C"
  icon: mdi:temperature-celsius
  device_class: temperature
  state_class: measurement
- platform: toptronic
  name: Fan exhaust air set
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 38600
  id: HV_50_0_38600
  type: U8
  unit_of_measurement: '%'
  icon: mdi:percent
  device_class: power_factor
  state_class: measurement
- platform: toptronic
  name: Maint.ctr.value message maint. (op. wks)
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 0
  function_number: 0
  datapoint: 20037
  id: HV_0_0_20037
  type: U32
- platform: toptronic
  name: Cleaning count value message cleaning (operating weeks)
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 0
  function_number: 0
  datapoint: 41613
  id: HV_0_0_41613
  type: U32
text_sensor:
- platform: toptronic
  name: Op. choice ventilation
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 40650
  id: HV_50_0_40650
  options:
  - Standby
  - Week 1
  - Week 2
  - Constant operation, setpoint 40651
  - Eco mode, setpoint DAP40686
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
- platform: toptronic
  name: Status vent. regulation
  device_type: HV
  device_addr: ${TT_HV_addr}
  function_group: 50
  function_number: 0
  datapoint: 39652
  id: HV_50_0_39652
  options:
  - Unit off, e.g. standby mode
  - Normal ventilation mode
  - VOC mode active
  - Humidity mode active
  - Frost protection active
  - CoolVet active
  - Fault status
  - Summer humidity
  - Switch-off stop set value
  values:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
