esphome:
  name: $name
  # on_boot:
  #   priority: 200  
  #   then:
  #     - wait_until:  
  #         condition:
  #           wifi.connected: 
  #         timeout: 15s
  #     - delay: 30s
  #     - script.execute: canbus_on_boot_requests # 1 time request is enough to get values until hoval reboot
  
esp32:
  board: az-delivery-devkit-v4 #nodemcu-32s #esp-wrover-kit 
  framework:
    type: esp-idf #arduino #esp-idf  not ready missing json and async_tcp
    version: recommended #latest
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

preferences:
  flash_write_interval: 60min
  
# Enable logging
logger:
  level: DEBUG #NONE# ERROR #INFO #DEBUG  #VERBOSE
  baud_rate: 0 #to disable logging via UART
  logs:
    text_sensor: ERROR
    homeassistant.sensor: ERROR
    canbus: ERROR # setting log level for canbus lower than INFO may crash  : esphome/issues#4051
    uptime: ERROR
    uptime.sensor: ERROR
    wifi_signal: ERROR
    wifi_signal.sensor: ERROR
    esp32.preferences: ERROR
    internal_temperature: ERROR
    esp-idf: ERROR
    select: ERROR
    number: ERROR
    sensor: INFO
    tt: INFO


# Enable Home Assistant API
api:
  reboot_timeout: 30min
      

ota:
  - platform: esphome

safe_mode:

