canbus:
  - platform: esp32_can
    id: cbus
    tx_pin: ${can_tx_pin} # GPIO22 #GPIO5
    rx_pin: ${can_rx_pin} # GPIO21 #GPIO4
    can_id: 0 # unused
    bit_rate: 50kbps # real rate of hoval canbus = min 300 to max 2400 baud.( 2400 x 8bits = 19200 bps)  Esphome with Esp32 cannot run under 50kbps
    on_frame:
    - can_id: 0 
      can_id_mask: 0 
      use_extended_id: true
      then:
      - lambda: |-
            id(tt).parse_frame(x, can_id, remote_transmission_request);

    ######### debug ###########
    #### CANDUMP : to debug only
    # - can_id: 0  # listen to all messages
      # can_id_mask: 0
      # use_extended_id: true
      # then:
      # - lambda: |-
            # ESP_LOGI("candump", "%x : %x %x %x %x %x %x %x %x", can_id, int(x[0]), int(x[1]), int(x[2]), int(x[3]), int(x[4]), int(x[5]), int(x[6]), int(x[7])); //1FD047FF   [8]  01 42 32 00 92 E2 00 FF
    
    #### Find can_id 
    # - can_id: 0  # listen to all messages
    #   can_id_mask: 0
    #   use_extended_id: true
    #   then:
    #   - lambda: |-
    #         if(x[1] == 0x42) { // response frame
    #             ESP_LOGI("can_id_find", "Response frame : hoval_homevent_can_Addr is probably : %x", can_id);
    #         }else if(x[1] == 0x40) { // request frame
    #             ESP_LOGI("can_id_find", "Request frame : hoval_toptronic_can_Addr is probably : %x", can_id);
    #         }

