number:
- platform: toptronic
  name: Temp ambiente normale riscaldamento (1)
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 1
  function_number: 0
  datapoint: 3051
  id: WEZ_1_0_3051_1481_set
  type: S16
  min_value: 100
  max_value: 300
  step: 5
  decimal: 1
  unit_of_measurement: "\xB0C"
  icon: mdi:temperature-celsius
  device_class: temperature
- platform: toptronic
  name: Temp ambiente risparmio riscaldamento (1)
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 1
  function_number: 0
  datapoint: 3053
  id: WEZ_1_0_3053_1482_set
  type: S16
  min_value: 50
  max_value: 200
  step: 5
  decimal: 1
  unit_of_measurement: "\xB0C"
  icon: mdi:temperature-celsius
  device_class: temperature
- platform: toptronic
  name: Temp ambiente normale riscaldamento (2)
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 1
  function_number: 1
  datapoint: 3051
  id: WEZ_1_1_3051_1483_set
  type: S16
  min_value: 100
  max_value: 300
  step: 5
  decimal: 1
  unit_of_measurement: "\xB0C"
  icon: mdi:temperature-celsius
  device_class: temperature
- platform: toptronic
  name: Temp ambiente risparmio riscaldamento (2)
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 1
  function_number: 1
  datapoint: 3053
  id: WEZ_1_1_3053_1484_set
  type: S16
  min_value: 50
  max_value: 200
  step: 5
  decimal: 1
  unit_of_measurement: "\xB0C"
  icon: mdi:temperature-celsius
  device_class: temperature
- platform: toptronic
  name: Temp ambiente normale riscaldamento (3)
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 1
  function_number: 2
  datapoint: 3051
  id: WEZ_1_2_3051_1485_set
  type: S16
  min_value: 100
  max_value: 300
  step: 5
  decimal: 1
  unit_of_measurement: "\xB0C"
  icon: mdi:temperature-celsius
  device_class: temperature
- platform: toptronic
  name: Temp ambiente risparmio riscaldamento (3)
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 1
  function_number: 2
  datapoint: 3053
  id: WEZ_1_2_3053_1486_set
  type: S16
  min_value: 50
  max_value: 200
  step: 5
  decimal: 1
  unit_of_measurement: "\xB0C"
  icon: mdi:temperature-celsius
  device_class: temperature
- platform: toptronic
  name: Temperatura acqua calda normale
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 2
  function_number: 0
  datapoint: 5051
  id: WEZ_2_0_5051_1497_set
  type: S16
  min_value: 100
  max_value: 700
  step: 10
  decimal: 1
  unit_of_measurement: "\xB0C"
  icon: mdi:temperature-celsius
  device_class: temperature
- platform: toptronic
  name: Temperatura di risparmio acqua calda
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 2
  function_number: 0
  datapoint: 5086
  id: WEZ_2_0_5086_1498_set
  type: U8
  min_value: 10
  max_value: 70
  step: 1
  decimal: 0
  unit_of_measurement: "\xB0C"
  icon: mdi:temperature-celsius
  device_class: temperature
select:
- platform: toptronic
  name: Selezione modo funzionam.to riscaldam.to (1)
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 1
  function_number: 0
  datapoint: 3050
  id: WEZ_1_0_3050_1478_set
  options:
  - Stand-by
  - Settimana 1
  - Settimana 2
  - Costante
  - Risparmio
  - Modo manuale riscaldare
  - Modo manuale raffreddare
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
  - 7
  - 8
- platform: toptronic
  name: Selezione modo funzionam.to riscaldam.to (2)
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 1
  function_number: 1
  datapoint: 3050
  id: WEZ_1_1_3050_1479_set
  options:
  - Stand-by
  - Settimana 1
  - Settimana 2
  - Costante
  - Risparmio
  - Modo manuale riscaldare
  - Modo manuale raffreddare
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
  - 7
  - 8
- platform: toptronic
  name: Selezione modo funzionam.to riscaldam.to (3)
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 1
  function_number: 2
  datapoint: 3050
  id: WEZ_1_2_3050_1480_set
  options:
  - Stand-by
  - Settimana 1
  - Settimana 2
  - Costante
  - Risparmio
  - Modo manuale riscaldare
  - Modo manuale raffreddare
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
  - 7
  - 8
- platform: toptronic
  name: Selezione modo funzionamento acqua calda
  device_type: WEZ
  device_addr: ${TT_WEZ_addr}
  function_group: 2
  function_number: 0
  datapoint: 5050
  id: WEZ_2_0_5050_1496_set
  options:
  - Stand-by
  - Settimana 1
  - Settimana 2
  - Costante
  - "Modalit\xE0 risparmio"
  values:
  - 0
  - 1
  - 2
  - 4
  - 6
