sensor:
- platform: toptronic
  name: Ambiente-effettivo
  device_type: BM
  device_addr: ${TT_BM_addr}
  device_id: ${TT_BM_device_id}
  function_group: 83
  function_number: 0
  datapoint: 0
  id: BM_83_0_0_0
  type: S16
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
  unit_of_measurement: "\xB0C"
  icon: mdi:temperature-celsius
  device_class: temperature
  state_class: measurement
binary_sensor: []
text_sensor: []
