# for flashing : press boot button for 2-3 seconds before the serial connection initialize
# After OTA update, the EN (reset) button must be pressed to run firmware
# do not use gpio12 (MTDI)

substitutions:
  name: canbus
  friendly_name: "CanBus Controller"
  TZ: "Europe/Zurich" #timezone
  
  ### canbus 
  can_tx_pin: "GPIO22" #GPIO5
  can_rx_pin: "GPIO21" #GPIO4

  ### Device list
  ### You can find it in room control unit (toptronic) under maintenance
  TT_HV_addr: "8"
  TT_BM_addr: "8"
  TT_WEZ_addr: "1"
  
  
external_components:
  - source:
      type: local
      path: components

packages:
  wifi: !include src/wifi.yaml
  board: !include src/board.yaml
  time: !include src/time.yaml
  canbus: !include src/canbus.yaml
  toptronic: !include src/toptronic.yaml
  sensors_others: !include src/sensors_others.yaml
  switch: !include src/switch.yaml
  # debug: !include src/debug.yaml
  
  ### Presets
  hv_sensors: !include src/preset/HV/sensors_en.yaml
  hv_inputs: !include src/preset/HV/inputs_en.yaml
  # wez_sensors: !include src/preset/WEZ/sensors_en.yaml
  # wez_inputs: !include src/preset/WEZ/inputs_en.yaml
  # bd_sensors: !include src/preset/BD/sensors_en.yaml

  
web_server:
  port: 80
  #log: false
